---

- name: Download certs from Cloudflare pki server
  hosts: etcd_servers
  become: yes
  become_user: root
  tasks:
    - name: Create SSL dir
      file:
        dest: "/etc/etcd"
        state: directory

    - name: Download SSL certs and keys
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      with_items:
        - url: "http://core1.lan/kubernetes.pem"
          dest: "/etc/etcd/kubernetes.pem"
        - url: "http://core1.lan/kubernetes-key.pem"
          dest: "/etc/etcd/kubernetes-key.pem"
        - url: "http://core1.lan/ca.pem"
          dest: "/etc/etcd/ca.pem"

- name: Download certs from Cloudflare pki server on controller servers
  hosts: controller_servers,worker_servers
  become: yes
  become_user: root
  tasks:
    - name: Create SSL dir
      file:
        dest: "/var/lib/kubernetes"
        recurse: yes
        state: directory

    - name: Download SSL certs and keys
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      with_items:
        - url: "http://core1.lan/kubernetes.pem"
          dest: "/var/lib/kubernetes/kubernetes.pem"
        - url: "http://core1.lan/kubernetes-key.pem"
          dest: "/var/lib/kubernetes/kubernetes-key.pem"
        - url: "http://core1.lan/ca.pem"
          dest: "/var/lib/kubernetes/ca.pem"
