---

- name: Expose precreated docker cert with Apache for worker nodes
  hosts: dreg0.lan
  become: yes
  become_user: root
  vars:
    global_dreg_ssl_cert_dir: "/etc/ssl"
    global_dreg_apache_dir: "/var/www/html"
  tasks:
    - name: Ensure Apache is present
      apt:
        name: apache2
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
    
    - name: Copy {{ global_dreg_ssl_cert_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.crt to {{ global_dreg_apache_dir }} apache dir
      copy:
        src: "{{ global_dreg_ssl_cert_dir }}/{{ inventory_hostname }}/{{ inventory_hostname }}.crt"
        dest: "{{ global_dreg_apache_dir }}/{{ inventory_hostname }}_registry.crt"
        remote_src: yes
